initial commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,19 +30,39 @@ jobs:
           registry: ghcr.io
           dockerfile: Dockerfile-prod
           tags: cra-test
-      - name: Deploy package to digitalocean
-        uses: appleboy/ssh-action@master
-        env:
-          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      deploy-api-1:
+  needs: build
+    runs-on: ubuntu-latest
+    steps:
+      # Droplets already have docker, doctl + auth, and curl installed
+      - name: Deploy api to DigitalOcean Droplet
+        uses: appleboy/ssh-action@v0.1.4
         with:
-          host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          host: ${{ secrets.DO_API1_HOST }}
+          username: root
+          key: ${{ secrets.DO_API_KEY }}
           port: 22
-          envs: GITHUB_USERNAME, GITHUB_TOKEN
           script: |
-            docker stop $(docker ps -a -q)
-            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
-            docker pull docker.pkg.github.com/my_github_username/my_repository_name/my_image_name:latest
-            docker run -dit -p 80:80 docker.pkg.github.com/my_github_username/my_repository_name/my_image_name:latest
+            doctl registry login --expiry-seconds 180
+            docker pull registry.digitalocean.com/<REGISTRY_NAME>/api:latest
+
+            echo "calling shutdown endpoint..."
+            curl --silent http://localhost/shutdown || true
+
+            echo "giving healthcheck time to fail..."
+            sleep 30 # ((unhealthy + 1) * interval)
+
+            docker stop api || true
+            docker rm api || true
+
+            echo "starting server instance..."
+            docker run -d \
+              --restart always \
+              -p 0.0.0.0:80:80 \
+              --name api \
+              registry.digitalocean.com/<REGISTRY_NAME>/api:latest
+
+            echo "giving healthcheck time to recover..."
+            sleep 40 # ((healthy + 1) * interval)
+
+            curl --silent --fail http://localhost/health
