auto-prefixer and worker-loader upgrades

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,39 +30,39 @@ jobs:
           registry: ghcr.io
           dockerfile: Dockerfile-prod
           tags: cra-test
-  deploy-api-1:
-    needs: build
-      runs-on: ubuntu-latest
-      steps:
-        # Droplets already have docker, doctl + auth, and curl installed
-        - name: Deploy api to DigitalOcean Droplet
-          uses: appleboy/ssh-action@v0.1.4
-          with:
-            host: ${{ secrets.DO_API1_HOST }}
-            username: root
-            key: ${{ secrets.DO_API_KEY }}
-            port: 22
-            script: |
-              doctl registry login --expiry-seconds 180
-              docker pull registry.digitalocean.com/<REGISTRY_NAME>/api:latest
+  # deploy-api-1:
+  #   needs: build
+  #     runs-on: ubuntu-latest
+    steps:
+      # Droplets already have docker, doctl + auth, and curl installed
+      - name: Deploy api to DigitalOcean Droplet
+        uses: appleboy/ssh-action@v0.1.4
+        with:
+          host: ${{ secrets.DO_API1_HOST }}
+          username: root
+          key: ${{ secrets.DO_API_KEY }}
+          port: 22
+          script: |
+            doctl registry login --expiry-seconds 180
+            docker pull registry.digitalocean.com/<REGISTRY_NAME>/api:latest
 
-              echo "calling shutdown endpoint..."
-              curl --silent http://localhost/shutdown || true
+            echo "calling shutdown endpoint..."
+            curl --silent http://localhost/shutdown || true
 
-              echo "giving healthcheck time to fail..."
-              sleep 30 # ((unhealthy + 1) * interval)
+            echo "giving healthcheck time to fail..."
+            sleep 30 # ((unhealthy + 1) * interval)
 
-              docker stop api || true
-              docker rm api || true
+            docker stop api || true
+            docker rm api || true
 
-              echo "starting server instance..."
-              docker run -d \
-                --restart always \
-                -p 0.0.0.0:80:80 \
-                --name api \
-                registry.digitalocean.com/<REGISTRY_NAME>/api:latest
+            echo "starting server instance..."
+            docker run -d \
+              --restart always \
+              -p 0.0.0.0:80:80 \
+              --name api \
+              registry.digitalocean.com/<REGISTRY_NAME>/api:latest
 
-              echo "giving healthcheck time to recover..."
-              sleep 40 # ((healthy + 1) * interval)
+            echo "giving healthcheck time to recover..."
+            sleep 40 # ((healthy + 1) * interval)
 
-              curl --silent --fail http://localhost/health
+            curl --silent --fail http://localhost/health
